--Q1. What is the total revenue generated by male vs. female customers? 
SELECT 
	gender,
	ROUND(SUM(purchase_amount), 2) AS revenue
FROM customer_behaviour.dbo.customer
GROUP BY gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT 
	customer_id
FROM customer_behaviour.dbo.customer
WHERE purchase_amount > (SELECT ROUND(AVG(purchase_amount), 2) FROM customer_behaviour.dbo.customer) AND discount_applied = 'Yes';

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5
	item_purchased AS product,
	ROUND(AVG(review_rating), 2) AS avg_review_rating,
	ROW_NUMBER() OVER (ORDER BY ROUND(AVG(review_rating), 2) DESC) AS ranking
FROM customer_behaviour.dbo.customer
GROUP BY item_purchased
ORDER BY avg_review_rating DESC;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping
SELECT
	shipping_type,
	ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer_behaviour.dbo.customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers
SELECT 
	subscription_status,
	COUNT(customer_id) AS total_customers,
	ROUND(AVG(purchase_amount), 2) AS avg_spend,
	ROUND(SUM(purchase_amount), 2) AS total_spend
FROM customer_behaviour.dbo.customer
GROUP BY subscription_status;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
WITH cte AS (
SELECT 
	customer_id,
	item_purchased,
	CASE WHEN discount_applied = 'Yes' THEN 1
		 ELSE 0 
	END AS discount
FROM customer_behaviour.dbo.customer
)

SELECT TOP 5
	item_purchased,
	ROUND((SUM(discount) * 100.00 / COUNT(customer_id)), 2)  AS percentage_bought_discount
FROM cte
GROUP BY item_purchased
ORDER BY percentage_bought_discount DESC;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH cust_seg AS (
SELECT 
	customer_id,
	CASE WHEN previous_purchases = 1 THEN 'New'
		 WHEN previous_purchases >= 2 AND previous_purchases <= 10 THEN 'Returning'
		 ELSE 'Loyal'
	END AS customer_seg
FROM customer_behaviour.dbo.customer
)

SELECT 
	customer_seg,
	COUNT(customer_id) AS total_customers
FROM cust_seg
GROUP BY customer_seg;

--Q8. What are the top 3 most purchased products within each category?
